### ISSUE TITLE
command line tool compilation fails

### ISSUE THREAD

**Issue by jsommers** [inria-muse/service-traceroute#1]
following the instructions in the top-level `README.md` and compiling the command line tool from the `cmd/servicetraceroute` folder (under my `GOPATH`, etc.), I get:

```
$ go build
servicetraceroute.go:12:2: cannot find package "tracetcp" in any of:
        /usr/lib/go-1.12/src/tracetcp (from $GOROOT)
        /home/jsommers/go/src/tracetcp (from $GOPATH)
$ 
```

You can see from the above that the golang version I'm using is 1.12.  I'm also using the default `GOPATH` on this host.

**Comment by wontoniii** [comment]
Hi Joel,
Thanks a lot for reporting the issue. The issue was due to some left overs from a previous organization of the code. I have update the project structure to better follow go's guidelines. The code should compile now, just follow the update README (there is a build.sh script now in the root of the project).
Do let me know if you incur in other problems. Thanks again!

**Comment by jsommers** [comment]
Builds very nicely now --- thanks a lot for your quick response!
